---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible, ansible-lint and ansible-review
  - pip install ansible
  - pip install ansible-review

  # Check ansible,  version
  - ansible --version
  - ansible-lint --version
  - ansible-review --version

script:
  # Continuous integration: syntax check
  - ansible-playbook moodlebox.yml --syntax-check -vvv

  # Continuous integration: ansible-lint
  - ansible-lint -p moodlebox.yml

  # Continuous integration: code review
  # - git ls-files *yml roles/ vars/ tests/  | xargs ansible-review

  # Continuous integration: code review diff between master and current branch
  # - git diff master | ansible-review

# notifications:
#   webhooks:
