---

- name: clone MoodleBox plugin from git repository
  git:
    repo: 'https://github.com/moodlebox/moodle-tool_moodlebox.git'
    dest: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox'
    version: '{{ moodlebox_moodlebox_plugin_version }}'

- name: touch files for MoodleBox plugin functionality
  file:
    path: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox/{{ item }}'
    state: 'touch'
  with_items:
    - '.reboot-server'
    - '.shutdown-server'
    - '.set-server-datetime'
    - '.newpassword'
    - '.wifisettings'

- name: change MoodleBox plugin file permissions
  file:
    path: '{{ moodlebox_moodle_source_dir }}/admin/tool/moodlebox'
    state: 'directory'
    owner: 'www-data'
    group: 'www-data'
    mode: 'ug+w,o-w'
    recurse: 'yes'

- name: install MoodleBox plugin via CLI
  command: '/usr/bin/php "{{ moodlebox_moodle_source_dir }}/admin/cli/upgrade.php"
    --allow-unstable
    --non-interactive'
  args:
    chdir: '{{ moodlebox_moodle_source_dir }}'
