moodlebox_install_packages:
  - iptables-persistent
  - hostapd
  - dnsmasq
  - git
  - ntfs-3g
  - exfat-fuse
  - lockfile-progs
  - incron
  - nginx
  - php7.0-fpm
  - php7.0-cli
  - php7.0-xmlrpc
  - php7.0-curl
  - php7.0-gd
  - php7.0-intl
  - php7.0-soap
  - php7.0-mysql
  - php-apcu
