moodlebox_install_packages:
  - iptables-persistent
  - hostapd
  - dnsmasq
  - git
  - ntfs-3g
  - exfat-fuse
  - lockfile-progs
  - incron
  - nginx
  - php7.1-fpm
  - php7.1-cli
  - php7.1-xmlrpc
  - php7.1-curl
  - php7.1-gd
  - php7.1-intl
  - php7.1-soap
  - php7.1-mysql
  - php-apcu
