moodlebox_install_packages:
  - iptables-persistent
  - hostapd
  - dnsmasq
  - git
  - ntfs-3g
  - exfat-fuse
  - lockfile-progs
  - incron
  - nginx
  - ghostscript
  - php7.1-fpm
  - php7.1-cli
  - php7.1-common
  - php7.1-json
  - php7.1-mbstring
  - php7.1-opcache
  - php7.1-readline
  - php7.1-xmlrpc
  - php7.1-curl
  - php7.1-gd
  - php7.1-intl
  - php7.1-soap
  - php7.1-mysql
  - php7.1-mcrypt
  - php7.1-xml
  - php7.1-zip
  - php7.1
  - php-apcu
