---

- name: uninstall useless packages
  apt:
    pkg: '{{ moodlebox_uninstall_packages }}'
    state: 'absent'
    purge: 'yes'
  when: 'moodlebox_uninstall_packages is defined'

- name: install packages
  apt:
    pkg: '{{ moodlebox_install_packages }}'
    state: 'present'
